[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    marcoschwartz/LiquidCrystal_I2C
    throwtheswitch/Unity

[env:native]
platform = native
lib_deps =
    throwtheswitch/Unity

; Test environments
[env:test-native]
platform = native
lib_deps =
    throwtheswitch/Unity
test_framework = unity

[env:test-esp32]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    marcoschwartz/LiquidCrystal_I2C
    throwtheswitch/Unity
test_framework = unity
test_speed = 115200
