[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    marcoschwartz/LiquidCrystal_I2C
    throwtheswitch/Unity

[env:native]
platform = native
test_build_src = no
lib_deps =
    throwtheswitch/Unity
